services:
  inference:
    image: jorgerguezz/lol-rag-inference:latest
    build:
      context: .
      dockerfile: docker/inference/Dockerfile
    container_name: gatv_inference
    working_dir: /app
    volumes:
      - ./models:/app/models
    ports:
      - "3000:3000"
      - "8000:8000"
    gpus: all
    stdin_open: true
    tty: true
